# .markdownlint-cli2.yaml
config:
  default: true
  MD013:
    line_length: 120
    code_blocks: false
    tables: false
  MD024: false          # Allow duplicate headings (common in standards)
  MD033: false          # Allow inline HTML
  MD034: false          # Allow bare URLs

ignores:
  - node_modules/**
  - "**/dist/**"
  - "**/build/**"
  - "**/target/**"
  - docker/**
